-- AUTO-GENERATED by scripts/check-canonical-functions.mjs — do not edit by hand.
-- Canonical definition of public.allocate_file_number as of migration 0040_allocate_file_number_consume_reservations.sql.
-- Regenerate after adding a migration that redefines it:
--   node scripts/check-canonical-functions.mjs --update

create or replace function allocate_file_number(p_year int default null, p_prefix text default null)
returns text language plpgsql security definer as $$
declare
  v_year   int;
  v_seq    bigint;
  v_prefix text;
  v_format text;
  v_result text;
begin
  v_year := coalesce(p_year, extract(year from (now() at time zone 'Africa/Johannesburg'))::int);

  -- Resolve prefix before sequence allocation so counters are prefix-specific.
  select coalesce(p_prefix, file_number_prefix), file_number_format
    into v_prefix, v_format
    from practice_settings where id = 1;

  -- Lock or insert this year's sequence row for this prefix.
  insert into file_number_sequences (year, prefix, next_value)
    values (v_year, v_prefix, 1)
    on conflict (year, prefix) do nothing;

  -- Lock the (year, prefix) row up front so the reservation consult and any counter
  -- increment serialize against concurrent onboards for the same (year, prefix).
  perform 1
    from file_number_sequences
    where year = v_year
      and prefix = v_prefix
    for update;

  -- Reservation consult: consume the lowest unconsumed reserved slot before the counter.
  -- Plain FOR UPDATE (no SKIP LOCKED): the sequence-row lock above already serializes
  -- same-(year, prefix) onboards, so this blocks on contention rather than skipping -- a
  -- skipped row would silently leave a reservation unconsumed and burn a counter value.
  select seq
    into v_seq
    from file_number_reservations
    where prefix = v_prefix
      and year = v_year
      and consumed_at is null
    order by seq
    limit 1
    for update;

  if found then
    -- Consume the reserved slot. Do NOT advance next_value on this path.
    update file_number_reservations
      set consumed_at = now()
      where prefix = v_prefix
        and year = v_year
        and seq = v_seq;
  else
    -- No reservation: existing counter-increment logic, unchanged.
    update file_number_sequences
      set next_value = next_value + 1
      where year = v_year
        and prefix = v_prefix
      returning next_value - 1 into v_seq;
  end if;

  v_result := replace(v_format, '{PREFIX}', v_prefix);
  v_result := replace(v_result, '{YYYY}', v_year::text);
  v_result := replace(v_result, '{SEQ:06}', lpad(v_seq::text, 6, '0'));

  return v_result;
end $$;
