-- AUTO-GENERATED by scripts/check-canonical-functions.mjs — do not edit by hand.
-- Canonical definition of public.current_app_role as of migration 20260928112841_client_baseline_security.sql.
-- Regenerate after adding a migration that redefines it:
--   node scripts/check-canonical-functions.mjs --update

create or replace function public.current_app_role()
returns public.role_name
language sql stable security definer
set search_path = ''
as $function$
  select r.name
  from public.app_users u
  join public.roles r on r.id = u.role_id
  where u.id = auth.uid() and u.status = 'active'
    and (auth.jwt()->>'aal') = 'aal2';
$function$;
