-- AUTO-GENERATED by scripts/check-canonical-functions.mjs — do not edit by hand.
-- Canonical definition of public.prevent_consent_record_mutation as of migration 0043_consent_records_immutable.sql.
-- Regenerate after adding a migration that redefines it:
--   node scripts/check-canonical-functions.mjs --update

create or replace function public.prevent_consent_record_mutation()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  raise exception 'consent_records are immutable: capture a new consent row instead of % on %',
    lower(tg_op), old.id
    using errcode = 'PT409';
end;
$$;
