-- AUTO-GENERATED by scripts/check-canonical-functions.mjs — do not edit by hand.
-- Canonical definition of public.prevent_finalised_clinical_note_mutation as of migration 0034_void_clinical_notes.sql.
-- Regenerate after adding a migration that redefines it:
--   node scripts/check-canonical-functions.mjs --update

create or replace function public.prevent_finalised_clinical_note_mutation()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if tg_op = 'DELETE' then
    if old.is_finalised then
      raise exception 'clinical_notes %: finalised notes cannot be deleted (supersede via amendment)', old.id
        using errcode = 'PT409';
    end if;
    return old;
  end if;

  if old.is_finalised = false and new.is_finalised = true then
    if new.encrypted_body is distinct from old.encrypted_body
       or new.nonce is distinct from old.nonce
       or new.encrypted_ink is distinct from old.encrypted_ink
       or new.ink_nonce is distinct from old.ink_nonce
       or new.dek_id is distinct from old.dek_id
       or new.patient_id is distinct from old.patient_id
       or new.author_user_id is distinct from old.author_user_id
       or new.note_date is distinct from old.note_date
       or new.amended_from_note_id is distinct from old.amended_from_note_id
       or new.voided_at is distinct from old.voided_at
       or new.voided_by is distinct from old.voided_by
       or new.void_reason is distinct from old.void_reason
       or new.created_at is distinct from old.created_at then
      raise exception 'clinical_notes %: content, identity, or void metadata cannot be modified while finalising', old.id
        using errcode = 'PT409';
    end if;
    return new;
  end if;

  if old.is_finalised then
    if current_setting('app.void_clinical_note', true) = 'on'
       and old.voided_at is null
       and new.is_finalised is true
       and new.voided_at is not null
       and new.voided_by = auth.uid()
       and length(btrim(coalesce(new.void_reason, ''))) >= 3
       and new.encrypted_body is not distinct from old.encrypted_body
       and new.nonce is not distinct from old.nonce
       and new.encrypted_ink is not distinct from old.encrypted_ink
       and new.ink_nonce is not distinct from old.ink_nonce
       and new.encrypted_ink_png is not distinct from old.encrypted_ink_png
       and new.ink_png_nonce is not distinct from old.ink_png_nonce
       and new.dek_id is not distinct from old.dek_id
       and new.patient_id is not distinct from old.patient_id
       and new.author_user_id is not distinct from old.author_user_id
       and new.note_date is not distinct from old.note_date
       and new.finalised_at is not distinct from old.finalised_at
       and new.amended_from_note_id is not distinct from old.amended_from_note_id
       and new.created_at is not distinct from old.created_at then
      return new;
    end if;

    raise exception 'clinical_notes %: finalised notes are immutable except for controlled voiding', old.id
      using errcode = 'PT409';
  end if;

  return new;
end;
$$;
