-- AUTO-GENERATED by scripts/check-canonical-functions.mjs — do not edit by hand.
-- Canonical definition of public.reassign_patient_hospital as of migration 0053_reassign_patient_hospital.sql.
-- Regenerate after adding a migration that redefines it:
--   node scripts/check-canonical-functions.mjs --update

create or replace function public.reassign_patient_hospital(
  p_patient_id   uuid,
  p_new_hospital text,
  p_reason       text
)
returns table (
  old_file_number text,
  new_file_number text,
  old_hospital    text,
  new_hospital    text,
  removed_pending_billing int
)
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
declare
  v_actor uuid := auth.uid();
  v_role public.role_name;
  v_patient public.patients%rowtype;
  v_new_prefix text;
  v_new_number text;
  v_reason text := btrim(coalesce(p_reason, ''));
  v_removed int := 0;
  v_old_prefix text;
  v_old_year int;
  v_old_seq bigint;
begin
  if v_actor is null then
    raise exception 'Not authenticated' using errcode = '42501';
  end if;

  v_role := (select public.current_app_role());
  if v_role is null or v_role not in ('doctor', 'staff') then
    raise exception 'file reassignment is restricted to staff and doctor'
      using errcode = '42501';
  end if;

  if length(v_reason) < 10 then
    raise exception 'a reason of at least 10 characters is required'
      using errcode = '22023';
  end if;

  select * into v_patient
    from public.patients
    where id = p_patient_id
    for update;
  if not found then
    raise exception 'patient not found' using errcode = 'PT404';
  end if;

  if v_patient.hospital = p_new_hospital then
    raise exception 'patient is already filed under %', p_new_hospital
      using errcode = 'PT409';
  end if;

  select h.file_prefix into v_new_prefix
    from public.hospitals h
    where h.name = p_new_hospital
      and h.active;
  if v_new_prefix is null then
    raise exception 'Invalid or inactive hospital value: %', coalesce(p_new_hospital, 'null')
      using errcode = '22023';
  end if;

  -- New number under the correct prefix (consults reservations per 0040).
  v_new_number := public.allocate_file_number(null, v_new_prefix);

  -- Retire the old number: history row (search + traceability)…
  insert into public.patient_file_number_history (
    patient_id, old_file_number, old_hospital,
    new_file_number, new_hospital, reason, changed_by
  ) values (
    p_patient_id, v_patient.file_number, v_patient.hospital,
    v_new_number, p_new_hospital, v_reason, v_actor
  );

  -- …and a poison pill so the retired slot can never be re-issued through the
  -- reservations path. Parsed from the {PREFIX}-{YYYY}-{SEQ} format; a legacy
  -- number that does not parse simply skips this guard (the sequence counter
  -- is already past it and patients.file_number uniqueness still holds).
  if v_patient.file_number ~ '^[A-Z]{2,5}-\d{4}-\d+$' then
    v_old_prefix := split_part(v_patient.file_number, '-', 1);
    v_old_year   := split_part(v_patient.file_number, '-', 2)::int;
    v_old_seq    := split_part(v_patient.file_number, '-', 3)::bigint;
    insert into public.file_number_reservations (prefix, year, seq, reason, consumed_at)
    values (v_old_prefix, v_old_year, v_old_seq,
            'retired by hospital reassignment of patient ' || p_patient_id, now())
    on conflict (prefix, year, seq) do update
      set consumed_at = coalesce(public.file_number_reservations.consumed_at, now());
  end if;

  update public.patients
     set hospital = p_new_hospital,
         file_number = v_new_number,
         updated_by = v_actor
   where id = p_patient_id;

  -- Drop PENDING billing rows snapshotted under the wrong hospital. Exported
  -- and returned rows are part of the disclosure record and stay untouched.
  delete from public.billing_export_items b
   where b.patient_id = p_patient_id
     and b.hospital = v_patient.hospital
     and b.status = 'pending';
  get diagnostics v_removed = row_count;

  old_file_number := v_patient.file_number;
  new_file_number := v_new_number;
  old_hospital := v_patient.hospital;
  new_hospital := p_new_hospital;
  removed_pending_billing := v_removed;
  return next;
end;
$$;
