-- AUTO-GENERATED by scripts/check-canonical-functions.mjs — do not edit by hand.
-- Canonical definition of public.stage_billing_export_items as of migration 0041_billing_export_payer_type.sql.
-- Regenerate after adding a migration that redefines it:
--   node scripts/check-canonical-functions.mjs --update

create or replace function public.stage_billing_export_items(
  p_actor_user_id uuid,
  p_hospital      text,
  p_export_month  date,
  p_patient_ids   uuid[]
)
returns integer
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_role  public.role_name;
  v_count integer;
begin
  v_role := (select public.current_app_role());
  if v_role is null or v_role not in ('doctor', 'staff') then
    raise exception 'billing export staging is restricted to staff and doctor'
      using errcode = '42501';
  end if;

  if p_export_month is distinct from date_trunc('month', p_export_month)::date then
    raise exception 'export_month must be the first day of the month';
  end if;

  insert into public.billing_export_items as bei (
    patient_id, hospital, export_month, file_number, patient_name,
    id_number, id_type, medical_aid_number, payer_type, status,
    created_by, updated_by, created_at, updated_at
  )
  select
    p.id,
    p.hospital,
    p_export_month,
    p.file_number,
    btrim(regexp_replace(concat_ws(' ', p.first_names, p.surname), '\s+', ' ', 'g')),
    p.id_number,
    p.id_type,
    ma.membership_number,
    p.payer_type,
    'pending'::public.billing_export_status,
    p_actor_user_id,
    p_actor_user_id,
    now(),
    now()
  from public.patients p
  left join public.patient_medical_aid ma on ma.patient_id = p.id
  where p.id = any(p_patient_ids)
    and p.hospital = p_hospital
    and p.status = 'active'
  on conflict (patient_id, hospital, export_month) do update
    set file_number        = excluded.file_number,
        patient_name       = excluded.patient_name,
        id_number          = excluded.id_number,
        id_type            = excluded.id_type,
        medical_aid_number = excluded.medical_aid_number,
        payer_type         = excluded.payer_type,
        updated_by         = excluded.updated_by,
        updated_at         = now();

  get diagnostics v_count = row_count;
  return v_count;
end;
$$;
