-- AUTO-GENERATED by scripts/check-canonical-functions.mjs — do not edit by hand.
-- Canonical definition of public.void_clinical_note as of migration 0034_void_clinical_notes.sql.
-- Regenerate after adding a migration that redefines it:
--   node scripts/check-canonical-functions.mjs --update

create or replace function public.void_clinical_note(
  p_note_id uuid,
  p_reason text
)
returns table (
  note_id uuid,
  patient_id uuid,
  voided_at timestamptz,
  voided_by uuid,
  void_reason text
)
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_reason text := btrim(coalesce(p_reason, ''));
  v_note public.clinical_notes%rowtype;
begin
  if p_note_id is null then
    raise exception 'note_id is required' using errcode = '22023';
  end if;

  if length(v_reason) < 3 then
    raise exception 'void reason must be at least 3 characters' using errcode = '22023';
  end if;

  if public.current_app_role() is distinct from 'doctor' then
    raise exception 'only doctors can void clinical notes' using errcode = '42501';
  end if;

  select * into v_note
  from public.clinical_notes cn
  where cn.id = p_note_id
  for update;

  if not found then
    raise exception 'clinical note not found' using errcode = 'PT404';
  end if;

  if not v_note.is_finalised then
    raise exception 'only finalised clinical notes can be voided' using errcode = 'PT409';
  end if;

  if v_note.voided_at is not null then
    raise exception 'clinical note is already voided' using errcode = 'PT409';
  end if;

  perform set_config('app.void_clinical_note', 'on', true);

  return query
    update public.clinical_notes cn
       set voided_at = now(),
           voided_by = auth.uid(),
           void_reason = v_reason,
           updated_at = now()
     where cn.id = p_note_id
     returning cn.id, cn.patient_id, cn.voided_at, cn.voided_by, cn.void_reason;
end;
$$;
