-- AUTO-GENERATED by scripts/check-canonical-functions.mjs — do not edit by hand.
-- Canonical definition of public.write_audit_entry as of migration 0024_audit_lock_non_blocking.sql.
-- Regenerate after adding a migration that redefines it:
--   node scripts/check-canonical-functions.mjs --update

create or replace function public.write_audit_entry(
  p_expected_prev_hash text,
  p_entry_hash         text,
  p_actor_user_id      uuid,
  p_actor_role         public.role_name,
  p_action             public.audit_action,
  p_entity_type        text,
  p_entity_id          uuid,
  p_patient_id         uuid,
  p_metadata_json      jsonb,
  p_ip_address         inet,
  p_user_agent         text,
  p_created_at         timestamptz
)
returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_tail_hash text;
  v_new_id    uuid;
begin
  -- Non-blocking: never wait on a stuck/aborted session that holds the chain
  -- lock. If we cannot take it immediately, raise 40001 so the caller retries
  -- (and falls back to the outbox) instead of hanging.
  if not pg_try_advisory_xact_lock(hashtext('dtm_audit_chain')) then
    raise exception 'audit chain lock busy' using errcode = '40001';
  end if;

  select entry_hash into v_tail_hash
    from public.audit_logs
    order by created_at desc, id desc
    limit 1;

  if coalesce(v_tail_hash, '') is distinct from coalesce(p_expected_prev_hash, '') then
    raise exception 'audit chain tail moved: expected=%, actual=%',
      coalesce(p_expected_prev_hash, '<null>'),
      coalesce(v_tail_hash, '<null>')
      using errcode = '40001';
  end if;

  insert into public.audit_logs (
    actor_user_id, actor_role, action, entity_type, entity_id,
    patient_id, metadata_json, ip_address, user_agent,
    created_at, prev_hash, entry_hash
  ) values (
    p_actor_user_id, p_actor_role, p_action, p_entity_type, p_entity_id,
    p_patient_id, coalesce(p_metadata_json, '{}'::jsonb), p_ip_address, p_user_agent,
    p_created_at, p_expected_prev_hash, p_entry_hash
  )
  returning id into v_new_id;

  return v_new_id;
end;
$$;
