-- Automatic seeds are disabled. The original DTM consent/contact seed is retired.
-- Historical migrations remain unchanged for existing installs.
-- Supply owner approved wording through config/client.example.json and
-- generate the guarded bootstrap with npm run client:prepare.
-- See docs/client-onboarding-runbook.md.
