-- Retired: the old script contained a production Auth UUID and could promote
-- existing accounts on rerun. No executable seed remains here.
-- Use client:prepare and generated initial-users.sql in the NEW project.
-- See docs/client-onboarding-runbook.md.
