import type { MetadataRoute } from "next";
import { Branding } from "@/lib/branding";

// Served at /manifest.webmanifest by Next 15 App Router.
// Replaces the previous static public/manifest.webmanifest.
//
// Notes:
//   • theme/background colour kept on the app's existing dark navy
//     (#050A16) to match the rest of the UI. The brand-green spec value
//     (#3B8560) is pending brand-owner sign-off — flip this single
//     constant if/when that's confirmed.
//   • Separate `any` and `maskable` icon entries per Android adaptive-icon
//     guidance. Combined "any maskable" causes either logo clipping or a
//     padded icon depending on the launcher; explicit purposes are safer.
//   • favicon-maskable-512.png is referenced but must be generated by hand
//     and visually verified in maskable.app/editor before upload — see the
//     PWA task brief, Phase 3.6.
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: Branding.appTitle,
    short_name: Branding.appName,
    description: Branding.appDescription,
    start_url: "/",
    scope: "/",
    display: "standalone",
    background_color: "#050A16",
    theme_color: "#050A16",
    orientation: "portrait",
    icons: [
      { src: "/icons/favicon-192x192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icons/favicon-512x512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      { src: "/icons/favicon-maskable-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
  };
}
