-- Storage buckets (§FR-9). Patient documents are stored with non-guessable
-- keys in the `patient-documents` bucket; access is via short-lived signed
-- URLs generated by the server after authorisation checks.

insert into storage.buckets (id, name, public)
values ('patient-documents', 'patient-documents', false)
on conflict (id) do nothing;

insert into storage.buckets (id, name, public)
values ('practice-brand', 'practice-brand', false)
on conflict (id) do nothing;

-- Only server-side (service_role) may read/write these buckets. Clients never
-- touch storage directly — they go through the API, which authorises and
-- returns a signed URL (§FR-9).
create policy "patient-documents deny all to authenticated"
  on storage.objects for all to authenticated
  using (bucket_id <> 'patient-documents')
  with check (bucket_id <> 'patient-documents');

create policy "practice-brand read to authenticated"
  on storage.objects for select to authenticated
  using (bucket_id = 'practice-brand');
